language: python
python:
  - "3.6"
install: "pip install https://github.com/openskynetwork/opensky-api/archive/master.zip#subdirectory=python"
script:
  - cd src
  - python unittest/python/openskyData_tests.py


